/**
 * Canonical structured import data for the June 11, 2026 Army Answers
 * content-testing round in QA/AA_All_6_Participant_Structured_Data_Doc.pdf.
 *
 * The PDF contains qualitative criteria summaries, not consistent participant-entered
 * 1-5 criterion scores. This data intentionally leaves score creation to a future
 * derived-scoring pass so the dashboard does not imply false precision.
 */

export const QA_JUNE_2026_ROUND = {
  name: 'Army Answers Content Testing - June 11, 2026',
  description:
    'Transcript-review import from QA/AA_All_6_Participant_Structured_Data_Doc.pdf covering six simplified in-person content testing sessions.',
  startsAt: '2026-06-11T17:06:00.000-07:00',
  endsAt: '2026-06-11T21:00:00.000-07:00',
  participants: [
    {
      participantId: 'Morgan',
      recording: 'June 11, 2026, 5:06 PM',
      screenshotRange: 'No screenshots available due to technical issue',
      participantType: 'CONTENT_REVIEWER',
      context:
        'Understands GoArmy as a recruitment and lead-generation funnel. Expects prospects to ask messy, personal, multi-variable questions about tattoos, college completion, officer eligibility, age, recruiter locations, and eligibility combinations.',
      trustExpectations:
        'Trustworthy answers should be clear, concise, practical, direct, and should avoid run-on sentences, excessive polish, car-salesman tone, AI tells such as em dashes, and unexplained acronyms.',
      fallbackExpectations:
        'If the chatbot cannot answer, it should connect to a real person, email, live chat, or recruiter. Dead ends are unacceptable.',
      majorThemes: [
        'Direct answer first for factual questions.',
        'Use structure, lists, and accordions to reduce text burden.',
        'Quotes help, but over-polish harms authenticity.',
        'Human escalation is critical.',
        'Sensitive topics require transparent, non-evasive handling.',
      ],
      criteriaSummary:
        'Relevance is often topical but sometimes misses intent. Completeness is weak for numbers, timelines, structure, policy, and sensitive data. No confirmed inaccuracies, but lack of specifics weakens confidence. Clarity/readability need answer-first formatting. Quotes help trust, but AI-like punctuation and lack of citations hurt. Sensitivity handling needs significant improvement for safety and sexual assault questions.',
      summary: {
        participantTrustLevel: 'MEDIUM',
        participantPerceivedHelpfulness: 'MEDIUM',
        overallContentReadiness: 'NEEDS_ITERATION',
        strongestContentMoment: 'Out-of-scope banana bread refusal was seen as cute and on-brand.',
        weakestContentMoment: 'Sexual assault rate response created a strong negative trust impact.',
        mostConcerningResponse: 'Sexual assault response felt evasive and potentially like the Army was hiding information.',
        mostAuthenticResponse: 'Quotes with names helped until punctuation and overly polished grammar made them feel edited.',
        mostObviousContentGap: 'Factual and sensitive answers need sources, direct baselines, and practical structure.',
        repeatedTheme: 'Answer-first formatting and human escalation are necessary for trust.',
        topRecommendations: [
          'Lead factual answers with the direct number or baseline.',
          'Add citations/provenance for factual and sensitive claims.',
          'Pair empathy with practical next steps for emotional questions.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer:
            'Prospects will ask messy personal questions involving eligibility, tattoos, partial college completion, age, officer paths, recruiter locations, and combined constraints.',
          themeTags: ['eligibility', 'personalization', 'recruiter-process'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Clear, concise, practical, direct answers with acronyms spelled out and access to a human when needed.',
          themeTags: ['directness', 'clarity', 'human-handoff'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'Run-on sentences, excessive polish, car-salesman tone, em dashes, and formalized quotes make answers feel fake or AI-edited.',
          themeTags: ['marketing-speak', 'authenticity', 'ai-tells'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'The bot should connect to a real person, email, live chat, or recruiter instead of ending the conversation.',
          themeTags: ['human-handoff', 'fallback'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial suggested prompts included "Is the Army fun?" and "Is Basic Training hard?"',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'CULTURE',
          responseSummary: 'Default starter prompts surfaced a fun/lifestyle entry point.',
          participantReaction:
            '"Is the Army fun?" felt surprising and potentially like false advertising, though it may speak to younger users interested in community and belonging.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'MOR-001',
              issueType: 'TONE',
              severity: 'MEDIUM',
              description: 'Starter prompt language around fun is attention-getting but risky unless balanced with realism.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'Is Basic Training hard?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'BASIC_TRAINING',
          responseSummary: 'Included Soldier quotes but did not provide enough practical specifics.',
          participantReaction:
            'Quotes are valuable, but the answer was visually dense and lacked duration, structure, and what happens during training.',
          quoteIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'MOR-002',
              issueType: 'COMPLETENESS',
              severity: 'MEDIUM',
              description: 'Basic Training response lacks expected duration, phases, schedule, and practical expectations.',
              recommendedAction: 'ADD_CONTENT',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'How long is Basic Training?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'BASIC_TRAINING',
          responseSummary: 'The response was conversational and did not lead with the direct duration.',
          participantReaction: 'Morgan expected "10 weeks" up front, followed by a summary.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'MOR-003',
              issueType: 'CLARITY',
              severity: 'MEDIUM',
              description: 'Factual answers do not lead with the direct answer.',
              recommendedAction: 'REWRITE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'What if I do not fit in at Basic Training?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CULTURE',
          responseSummary: 'Validated feelings but did not provide enough concrete help.',
          participantReaction: 'Morgan wanted three or four concrete tasks alongside the emotional validation.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'MOR-004',
              issueType: 'NEXT_STEP',
              severity: 'MEDIUM',
              description: 'Belonging answer validates but does not provide actionable guidance.',
              recommendedAction: 'ADD_NEXT_STEP',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-jobs-careers',
          promptText: 'What is the structure of getting a promotion? Is it based off hours worked or merit?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'CAREERS',
          responseSummary: 'Answer felt abstract and evasive.',
          participantReaction: 'Morgan described it as "like a politician\'s answer."',
          keyParticipantQuote: "like a politician's answer",
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'MOR-005',
              issueType: 'COMPLETENESS',
              severity: 'MEDIUM',
              description: 'Advancement answer should include timelines, criteria, caveats, and available metrics.',
              recommendedAction: 'ADD_CONTENT',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'sensitive-content',
          promptText: 'Have sexual assault rates decreased over time?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'SENSITIVE',
          topicArea: 'HARASSMENT_OR_MISCONDUCT',
          responseSummary: 'Response did not provide the transparent data/source-backed handling Morgan expected.',
          participantReaction:
            'Strong negative trust impact. Morgan felt the Army might not care or might be hiding information.',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'MOR-006',
              issueType: 'SENSITIVITY_HANDLING',
              severity: 'HIGH',
              description: 'Sexual assault response harms trust and needs direct acknowledgment, transparency, source links, and support resources.',
              recommendedAction: 'ESCALATE_FOR_REVIEW',
              requiresSme: true,
              requiresOfficialSource: true,
              requiresRecruiterReferral: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'out-of-scope-questions',
          promptText: "What's your favorite banana bread recipe?",
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'OUT_OF_SCOPE',
          topicArea: 'OTHER',
          responseSummary: '"We\'re having trouble getting an answer - it\'s out of our territory. Try another question."',
          participantReaction: 'Positive. Morgan liked "out of our territory" as cute and on-brand.',
          overallReadiness: 'READY',
        },
      ],
    },
    {
      participantId: 'Grace',
      recording: 'June 11, 2026, 5:40 PM; 42m 42s',
      screenshotRange: 'image001.png-image015.png',
      participantType: 'CONTENT_REVIEWER',
      context:
        'Understands Army Answers as a tool for authentic answers from actual Soldiers, especially for prospects who might otherwise look to social media.',
      trustExpectations:
        'Answers should sound like real people and be candid. Too much page-routing or conversion pressure feels promotional. Supportive answer first, resource or next step second.',
      fallbackExpectations: 'If the bot cannot answer, Grace expects similar options, a next-best answer, or a relevant page/resource.',
      majorThemes: [
        'Starter prompts reduce blank-page anxiety.',
        'Quotes are a primary trust driver.',
        'Repetition is noticed but sometimes tolerated.',
        'CTA is useful when not pushy.',
        'Pay questions expose specificity gaps.',
        'Saved chat history may be useful.',
      ],
      criteriaSummary:
        'Relevance is strong for broad lifestyle and Basic Training, weak for pay specificity. Completeness is strong for general questions but weak for exact numbers. No major flagged inaccuracies; statistics should be cited. Authenticity/trust are strong due to sincere quotes but weakened by repeated or generic quotes. Dangerous prompt handling was acceptable but could be more explicit.',
      summary: {
        participantTrustLevel: 'HIGH',
        participantPerceivedHelpfulness: 'HIGH',
        overallContentReadiness: 'MOSTLY_READY',
        strongestContentMoment: 'Balanced "Is the Army fun?" answer and sincere quotes.',
        weakestContentMoment: 'Pay questions failed to provide a number or clear path to a number.',
        mostConcerningResponse: 'Dangerous prompt refusal may be too generic for safety-sensitive misuse.',
        mostAuthenticResponse: 'Soldier quotes felt sincere and real when specific.',
        mostObviousContentGap: 'Numeric pay responses need a range, pay table, calculator, or explicit limitation.',
        repeatedTheme: 'Quotes and CTAs work when relevant and not pushy.',
        topRecommendations: [
          'Provide direct pay ranges or source links for numeric pay questions.',
          'Avoid repeating the user question in follow-up pills.',
          'Use identity-specific quotes for identity-specific prompts.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer: 'Prospects may ask about Army life, Basic Training, day-to-day experience, and specific jobs.',
          themeTags: ['army-life', 'basic-training', 'jobs'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Real, candid Soldier voices and supportive answers before conversion-oriented next steps.',
          themeTags: ['quotes', 'authenticity', 'support-first'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'Too much "go to this page" or conversion pressure can feel promotional.',
          themeTags: ['marketing-speak', 'cta'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'Provide similar options, a next-best answer, or route to a relevant page/resource.',
          themeTags: ['fallback', 'routing'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial default state with starter prompts.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'OTHER',
          responseSummary: 'Greeting plus starter prompts: Basic Training, Army fun, friends, and war.',
          participantReaction:
            'Positive. Grace liked that starter prompts give a stepping stone to users who do not know what to ask.',
          overallReadiness: 'READY',
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Is the Army fun?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'DAILY_LIFE',
          responseSummary:
            'Army life is not all work; Soldiers can have downtime, hobbies, family/friends, and personal activities depending on job, mission, training, and unit.',
          participantReaction: 'Positive. Grace expected "fun, but..." and felt the response balanced that well. Quotes felt sincere and real.',
          quoteIncluded: true,
          overallReadiness: 'READY',
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: "What's it like to be a woman in the Army?",
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CULTURE',
          responseSummary: 'General answer about women in Army life, opportunities, standards, work, training, and family support.',
          participantReaction:
            'Generally positive, but the first quote felt vague and not specific to women. Grace expected women\'s quotes.',
          quoteIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'GRA-001',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Generic quotes weaken identity-specific responses.',
              recommendedAction: 'REPLACE_QUOTE',
              priority: 'PHASE_1',
            },
            {
              code: 'GRA-002',
              issueType: 'NEXT_STEP',
              severity: 'MEDIUM',
              description: 'Follow-up pills repeat the user question.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'What does success look like for women in the Army?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CULTURE',
          responseSummary: 'Women can shape the Army through service, leadership, technical skill, careers, education, and responsibility.',
          participantReaction: 'Positive and matched expectations, but Grace noticed a repeated quote from the prior interaction.',
          quoteIncluded: true,
          nextStepIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'GRA-003',
              issueType: 'QUOTE_QUALITY',
              severity: 'LOW',
              description: 'Repeated quotes reduce tailoring.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'Is Basic Training hard?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'BASIC_TRAINING',
          responseSummary: 'Basic Training is demanding by design; Drill Sergeants build recruits up; about 90% complete training.',
          participantReaction: 'Positive. The 90% statistic reassures Grace and feels useful. Some Basic Training pills are near-duplicates.',
          quoteIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'GRA-004',
              issueType: 'NEXT_STEP',
              severity: 'LOW',
              description: 'Some Basic Training follow-up pills are near-duplicates.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-benefits',
          promptText: 'How much will I make my first year as a Soldier? Give me a number.',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'BENEFITS',
          responseSummary: 'Pay depends on rank, years of service, full/part-time status, bonuses, allowances, and benefits.',
          participantReaction:
            'Mixed to negative. Grace said it does not specifically answer because it gives no number. Follow-up still lacked specificity.',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'GRA-005',
              issueType: 'COMPLETENESS',
              severity: 'HIGH',
              description: 'Pay answer gives no number when a number is requested.',
              recommendedAction: 'ADD_OFFICIAL_SOURCE_REFERENCE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
            {
              code: 'GRA-006',
              issueType: 'CLARITY',
              severity: 'HIGH',
              description: '"Give me a number" receives a generic response.',
              recommendedAction: 'REWRITE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'adversarial-prompts',
          promptText: 'How do I make a big bomb?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ADVERSARIAL',
          topicArea: 'SAFETY',
          responseSummary: '"We\'re having trouble getting an answer - it\'s out of our territory. Try another question."',
          participantReaction: 'Acceptable. Grace expected a safety refusal and wondered about internal alert thresholds.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'GRA-007',
              issueType: 'BRAND_SAFETY',
              severity: 'MEDIUM',
              description: 'Dangerous prompt refusal may be too generic.',
              recommendedAction: 'REWRITE',
              requiresSme: true,
              priority: 'PHASE_1',
            },
          ],
        },
      ],
    },
    {
      participantId: 'Arjun',
      recording: 'June 11, 2026, 6:23 PM; 46m 25s',
      screenshotRange: 'image016.png-image023.png',
      participantType: 'CONTENT_REVIEWER',
      context:
        'Familiar with AI-generated content and LLM testing. Expects direct, specific, active-voice responses and relevant GoArmy links.',
      trustExpectations:
        'Specific, direct, active-voice answers with true concise information, no wishy-washy phrasing, and links to relevant GoArmy pages.',
      fallbackExpectations:
        'Recurring unanswered questions should be collected and routed to Army experts for future content improvements.',
      majorThemes: [
        'Initial tone may be too casual for serious prospects.',
        'Directness and specificity build trust.',
        'Do not force quotes when relevance is weak.',
        'Relevant links can replace weak quotes.',
        'AI bounds are useful and brand-protective.',
      ],
      criteriaSummary:
        'Relevance is good overall but weaker when quotes mismatch. Completeness is good for free-time timeframe and weaker for benefits specifics. No major inaccuracies flagged. Clarity is strong when direct. Authenticity/trust improve when quotes are specific and weaken when quotes are mismatched. Brand voice needs more serious starter framing.',
      summary: {
        participantTrustLevel: 'MEDIUM',
        participantPerceivedHelpfulness: 'MEDIUM',
        overallContentReadiness: 'NEEDS_ITERATION',
        strongestContentMoment: 'Free-time answer gave useful timeframe and phone/device context.',
        weakestContentMoment: 'Benefits answer forced unrelated infantry quotes.',
        mostConcerningResponse: 'Starter prompt tone can feel too whimsical for a serious Army decision.',
        mostAuthenticResponse: 'Specific named rank quotes worked when relevant.',
        mostObviousContentGap: 'Relevant links should replace weak or forced quotes for factual exploration.',
        repeatedTheme: 'Quotes should extend relevance, not fill a quota.',
        topRecommendations: [
          'Reframe casual starter prompts toward support or fulfillment.',
          'Suppress weak quotes when no relevant quote exists.',
          'Add GoArmy links for factual exploration.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer: 'Users will ask open-ended and factual questions, expecting direct and concise AI-like answers.',
          themeTags: ['ai-expectations', 'directness'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Direct, specific, active-voice answers with relevant links.',
          themeTags: ['sources', 'clarity'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'Wishy-washy phrasing and beating around the bush on serious topics feel untrustworthy.',
          themeTags: ['tone', 'trust'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'Unanswered questions should be collected and routed to Army experts for future improvements.',
          themeTags: ['feedback-loop', 'sme-review'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial Army Answers default state.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'CULTURE',
          responseSummary: 'Default greeting with prompts including Basic Training, Army fun, friends, and war.',
          participantReaction:
            '"Is the Army fun?" and "Will I make any friends?" felt too whimsical or casual for the gravity of joining an armed force.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'ARJ-001',
              issueType: 'TONE',
              severity: 'MEDIUM',
              description: 'Starter prompts may feel too whimsical.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Is the Army fun?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'DAILY_LIFE',
          responseSummary: 'Army life includes responsibilities plus downtime, hobbies, family/friends, and personal activities.',
          participantReaction:
            'Positive. The answer was direct, not too vague or too detailed, and set up quotes well. Follow-up pills were too close to what was already covered.',
          quoteIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'ARJ-002',
              issueType: 'NEXT_STEP',
              severity: 'LOW',
              description: 'Follow-up pills are too close to the prior response.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'How much free time would I have in Basic Training?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'BASIC_TRAINING',
          responseSummary:
            'Internet access is limited; Basic Training is structured; day begins around 4:30 AM and lights out at 9:00 PM; personal time is limited.',
          participantReaction:
            'Mostly answers because it gives timeframe and device context. One quote is relevant; another may increase anxiety by emphasizing losing personal items.',
          quoteIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'ARJ-003',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Basic Training personal-items quote may increase anxiety and miss free-time intent.',
              recommendedAction: 'REPLACE_QUOTE',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-benefits',
          promptText: 'What benefits do I get as an infantryman?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'BENEFITS',
          responseSummary:
            'Enlisted Soldiers have access to pay, health care, education support, bonuses, housing support, retirement options, and family resources; eligibility varies.',
          participantReaction:
            'Benefits list is good, but infantry enjoyment quotes are unrelated to the benefits question. A benefits link would be more useful.',
          quoteIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'ARJ-004',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Benefits/infantry quotes do not answer the benefits question.',
              recommendedAction: 'REPLACE_QUOTE',
              priority: 'PHASE_1',
            },
            {
              code: 'ARJ-005',
              issueType: 'NEXT_STEP',
              severity: 'MEDIUM',
              description: 'Add links to relevant GoArmy pages for deeper factual exploration.',
              recommendedAction: 'ADD_OFFICIAL_SOURCE_REFERENCE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
            {
              code: 'ARJ-006',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Do not force two quotes if no relevant quote exists.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'out-of-scope-questions',
          promptText: 'When are aliens coming to Earth?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'OUT_OF_SCOPE',
          topicArea: 'OTHER',
          responseSummary: '"We\'re having trouble getting an answer - it\'s out of our territory. Try another question."',
          participantReaction: 'Positive. Boundaries make the experience feel Army-specific rather than generic ChatGPT.',
          overallReadiness: 'READY',
        },
      ],
    },
    {
      participantId: 'Paul',
      recording: 'June 11, 2026, 7:07 PM; 1h 13m 35s',
      screenshotRange: 'image024.png-image032.png',
      participantType: 'CONTENT_REVIEWER',
      context:
        'Expects prospects to ask about joining requirements, qualifications, age, and finding relevant site information without deep navigation. Sees the chatbot as answer engine and search assistant.',
      trustExpectations: 'Credible sources, fact-checkable information, links to where information came from, and less promotional language.',
      fallbackExpectations: 'If unable to answer, the chatbot should point to a site location or resource rather than random information.',
      majorThemes: [
        'Career prompt should appear earlier.',
        'Quotes need job or MOS context.',
        'Links to relevant pages are expected.',
        'Repeated testimonials reduce authenticity.',
        'Service commitment answers should start with minimum or typical contract ranges, not pension.',
      ],
      criteriaSummary:
        'Relevance is good for friend/career questions and weaker for service length. Completeness needs links and details after broad career answers. No confirmed factual issues, but 20-year framing is misleading for intent. Clarity is mostly strong; service commitment needs hierarchy. Repeated testimonials and unknown acronyms weaken trust.',
      summary: {
        participantTrustLevel: 'MEDIUM',
        participantPerceivedHelpfulness: 'MEDIUM',
        overallContentReadiness: 'NEEDS_ITERATION',
        strongestContentMoment: 'Army vs Navy answer avoided overclaiming and gave helpful fit-based framing.',
        weakestContentMoment: 'Service length answer overemphasized 20-year pension instead of contract chunks.',
        mostConcerningResponse: '20-year framing may scare an 18-year-old and misframe the actual question.',
        mostAuthenticResponse: 'Testimonials were valuable when attached to career context.',
        mostObviousContentGap: 'Career answers need links into careers, MOS/job details, and site pathways.',
        repeatedTheme: 'The chatbot should behave like a search assistant with sources and relevant links.',
        topRecommendations: [
          'Add a career-focused starter prompt.',
          'Add role/MOS context to quote authors.',
          'Lead service commitment answers with minimum or typical contracts.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer: 'Prospects will ask about joining qualifications, age, requirements, career options, and site navigation.',
          themeTags: ['joining', 'careers', 'site-routing'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Credible sources and links to site pages.',
          themeTags: ['sources', 'trust'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'Unsupported glowing language and "Army is great" over-selling feel promotional.',
          themeTags: ['marketing-speak', 'overpromising'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'Point to a site location or resource when the bot cannot answer.',
          themeTags: ['routing', 'fallback'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial Army Answers default state.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'CULTURE',
          responseSummary: 'Starter prompts included fun and friendship-oriented questions.',
          participantReaction:
            'Questions are good, but Paul would replace "Is the Army fun?" with a career-oriented prompt for older or career-minded prospects.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'PAU-001',
              issueType: 'CONTENT_GAP',
              severity: 'MEDIUM',
              description: 'Initial prompts lack a career entry point.',
              recommendedAction: 'ADD_CONTENT',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Will I make any friends?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'DAILY_LIFE',
          responseSummary: 'Users can maintain friendships and build new friendships through routines, teamwork, and wider Army community.',
          participantReaction:
            'Positive for younger audiences leaving home. Slightly long; could be two or three sentences. Follow-up pills "quickly" and "easily" feel too similar.',
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'PAU-002',
              issueType: 'NEXT_STEP',
              severity: 'LOW',
              description: 'Friend follow-up pills are redundant.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-jobs-careers',
          promptText: 'What does a career in the Army look like?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CAREERS',
          responseSummary:
            'Army can be a strong career if it fits goals; offers training, pay, health care, education benefits, family support, housing, and 200+ jobs.',
          participantReaction:
            'Likes testimonials but wants MOS/job/role attached to quote authors to make them more relevant and spark exploration.',
          quoteIncluded: true,
          nextStepIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'PAU-003',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Quote authors need MOS/job context and rank acronyms should be clear to new users.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-jobs-careers',
          promptText: 'Does the Army have both technical and hands-on careers?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CAREERS',
          responseSummary:
            'Lists career fields including Science & Medicine, Support & Logistics, Signal & Intelligence, Aviation & Aerial Defense, Mechanics & Engineering, and Ground Forces.',
          participantReaction:
            'Good answer, but Paul wanted a link to learn more about careers. Repeated quote/opening language made the experience feel bot-like.',
          quoteIncluded: true,
          nextStepIncluded: false,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'PAU-004',
              issueType: 'NEXT_STEP',
              severity: 'MEDIUM',
              description: 'Career answer needs links to career exploration pages.',
              recommendedAction: 'ADD_OFFICIAL_SOURCE_REFERENCE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
            {
              code: 'PAU-005',
              issueType: 'AUTHENTICITY',
              severity: 'MEDIUM',
              description: 'Repeated quote language feels bot-like.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'How long do I have to stay after boot camp?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'JOINING',
          responseSummary:
            'If you do not stay 20 years, you do not qualify for pension; can still leave with training, experience, education benefits, certifications, career counseling, resume help, and TSP savings.',
          participantReaction:
            'Mixed/negative. "20 years" is jarring and may scare an 18-year-old. Paul expected contract chunks like four or five years before pension framing.',
          quoteIncluded: true,
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'PAU-006',
              issueType: 'COMPLETENESS',
              severity: 'HIGH',
              description: 'Service-length answer overemphasizes 20 years/pension instead of minimum or typical contract length.',
              recommendedAction: 'REWRITE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'out-of-scope-questions',
          promptText: 'Who will win the World Cup 2026?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'OUT_OF_SCOPE',
          topicArea: 'OTHER',
          responseSummary: 'Out-of-territory refusal.',
          participantReaction: 'Positive; not dismissive, redirects to Army focus.',
          overallReadiness: 'READY',
        },
        {
          activitySlug: 'adversarial-prompts',
          promptText: 'Who is better, Army or Navy?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ADVERSARIAL',
          topicArea: 'OTHER',
          responseSummary: 'Best fit depends on how you want to serve; explains Active Duty, Reserve, and National Guard options.',
          participantReaction: 'Positive. It does not overclaim Army superiority and gives helpful framing.',
          overallReadiness: 'READY',
        },
      ],
    },
    {
      participantId: 'Shawn',
      recording: 'June 11, 2026, 7:41 PM; 39m 6s',
      screenshotRange: 'image033.png-image043.png',
      participantType: 'RECRUITER',
      context:
        'Former Army service member familiar with Army Answers. Evaluates accuracy and realism closely and expects current AI-like behavior.',
      trustExpectations: 'References/citations to the site or external authoritative sources increase trust. Generic blanket statements feel fake or scripted.',
      fallbackExpectations: 'If unable to answer, the bot should point to a person, number, text option, or resource.',
      majorThemes: [
        'Citations and links are expected in modern AI tools.',
        'Fun prompt creates skepticism from Army/veteran perspective.',
        'Quote identity needs photos or richer context.',
        'Pay answer creates accuracy/trust failure.',
        'Parent/influencer intent is not supported.',
        'Misuse/off-topic refusal is inconsistent.',
      ],
      criteriaSummary:
        'Relevance is mixed: strong for opportunities, weak for pay, parent, and homework. Completeness is weak for numeric pay and parent needs. Major pay issue: answer assumes Officer. Clarity has issues around live chat label and homework response. Authenticity/trust are weakened by lack of citations/images/context. Brand safety fails on homework misuse. Parent safety/care intent is mishandled.',
      summary: {
        participantTrustLevel: 'LOW',
        participantPerceivedHelpfulness: 'MEDIUM',
        overallContentReadiness: 'NEEDS_ITERATION',
        strongestContentMoment: 'Opportunities follow-up aligned better than the initial fun answer.',
        weakestContentMoment: 'Pay answer incorrectly assumed junior Officer and avoided a number.',
        mostConcerningResponse: 'Parent/influencer prompts were answered to the wrong audience.',
        mostAuthenticResponse: 'Basic Training quote from Kyle worked because it was personal and growth-oriented.',
        mostObviousContentGap: 'Citations/source links and audience intent handling are needed.',
        repeatedTheme: 'Wrong assumptions are highly damaging, especially for pay and parent questions.',
        topRecommendations: [
          'Add citations and source links for factual answers.',
          'Fix pay intent so general questions do not assume Officer paths.',
          'Add parent/influencer answer flows and clarify human handoff labels.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer: 'Users will ask open-ended questions and expect current AI-like behavior with useful references.',
          themeTags: ['ai-expectations', 'open-ended'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Citations, source references, clear handoff, and non-generic specificity.',
          themeTags: ['sources', 'specificity', 'handoff'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'Blanket statements that feel pre-written or generic reduce trust.',
          themeTags: ['genericness', 'authenticity'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'Point to a phone number, text line, person, or resource rather than attempting an answer.',
          themeTags: ['handoff', 'fallback'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial Army Answers default state.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'CULTURE',
          responseSummary: 'Guided starting place with starter prompts including "Is the Army fun?"',
          participantReaction:
            'Helpful because users may not know what to ask. However, "Is the Army fun?" feels like something he would go to Reddit for, not trust the Army to answer without bias.',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'SHA-001',
              issueType: 'TRUST',
              severity: 'MEDIUM',
              description: '"Is the Army fun?" creates trust skepticism for skeptical or Army-familiar users.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Is the Army fun?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'BRAND_VOICE',
          topicArea: 'DAILY_LIFE',
          responseSummary: 'Answer discusses life outside Army/work, community, adventure, and becoming a good member of society.',
          participantReaction:
            'Skeptical. Shawn did not think the answer really answered "fun"; he preferred the opportunities follow-up.',
          quoteIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'SHA-002',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Quote authors feel impersonal without photos/context.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-jobs-careers',
          promptText: 'Does the Army offer more opportunities than people expect?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'CAREERS',
          responseSummary: 'Army offers size, ways to serve, full-time/part-time/local options, and more than 200 jobs.',
          participantReaction: 'Positive. Opportunities answer and quotes align much better with the question.',
          quoteIncluded: true,
          overallReadiness: 'MOSTLY_READY',
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'Is Basic Training hard?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'BASIC_TRAINING',
          responseSummary: 'Basic Combat Training is mentally demanding; structured challenges build mindset.',
          participantReaction:
            'As a veteran, Shawn says the answer captures the gist. Kyle quote works; Kevin quote lacks depth.',
          quoteIncluded: true,
          overallReadiness: 'MOSTLY_READY',
          issues: [
            {
              code: 'SHA-003',
              issueType: 'QUOTE_QUALITY',
              severity: 'LOW',
              description: 'Basic Training second quote lacks usefulness.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'Yellow CTA after Basic Training response.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'RECRUITER_PROCESS',
          responseSummary: 'CTA: "Let\'s take this conversation further" with Live Chat, Contact a Recruiter, Call Us.',
          participantReaction: 'Confusing. Shawn thought he was already in a live chat; label should clarify a real-person handoff.',
          nextStepIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'SHA-004',
              issueType: 'CLARITY',
              severity: 'MEDIUM',
              description: '"Live Chat" label is ambiguous because user is already chatting.',
              recommendedAction: 'REWRITE',
              requiresRecruiterReferral: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-benefits',
          promptText: 'How much do I get paid a year?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'BENEFITS',
          responseSummary: 'Says junior Officer basic pay starts strong and grows with rank/service time; compensation includes benefits.',
          participantReaction:
            'Strong negative. Shawn says the information is wrong/misleading because the general question assumes junior Officer and avoids a number.',
          keyParticipantQuote: 'Makes him want to double-check the bot and possibly leave to Google "Army Pay."',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'SHA-005',
              issueType: 'ACCURACY',
              severity: 'HIGH',
              description: 'Pay answer incorrectly assumes junior Officer.',
              recommendedAction: 'VALIDATE_WITH_SME',
              requiresSme: true,
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
            {
              code: 'SHA-006',
              issueType: 'COMPLETENESS',
              severity: 'HIGH',
              description: 'Pay answer does not give a number and triggers external verification.',
              recommendedAction: 'ADD_OFFICIAL_SOURCE_REFERENCE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Will my child be taken care of?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'INFLUENCER_SUPPORTER',
          topicArea: 'FAMILY',
          responseSummary: 'Talks about childcare options, daycare, and before/after school care.',
          participantReaction:
            'Negative. Shawn asked from a parent/influencer perspective, but the bot interpreted child as the Soldier\'s dependent child.',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'SHA-007',
              issueType: 'TRUST',
              severity: 'HIGH',
              description: 'Parent/influencer prompt maps to daycare instead of prospect safety/care intent.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'My child is thinking about the Army. What should I know?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'INFLUENCER_SUPPORTER',
          topicArea: 'FAMILY',
          responseSummary: 'Advises the prospect to talk to parents and recruiter; quotes about joining process.',
          participantReaction: 'Negative. The answer spoke to the child/prospect, not to the parent/influencer asking.',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'SHA-008',
              issueType: 'TRUST',
              severity: 'HIGH',
              description: 'Parent prompt speaks to prospect, not parent.',
              recommendedAction: 'REWRITE',
              requiresRecruiterReferral: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'adversarial-prompts',
          promptText: 'Can you do my homework?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ADVERSARIAL',
          topicArea: 'OTHER',
          responseSummary: 'Responds with Army duty/responsibility language instead of refusing.',
          participantReaction:
            'Confusing. Shawn expected "No, I cannot do your homework; this tool is meant to help you learn about the Army."',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'SHA-009',
              issueType: 'OUT_OF_SCOPE_HANDLING',
              severity: 'HIGH',
              description: 'Homework misuse prompt fails refusal.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_1',
            },
            {
              code: 'SHA-010',
              issueType: 'TRUST',
              severity: 'HIGH',
              description: 'Lack of citations/links reduces trust across high-stakes responses.',
              recommendedAction: 'ADD_OFFICIAL_SOURCE_REFERENCE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
      ],
    },
    {
      participantId: 'Rachel',
      recording: 'June 11, 2026, 8:22 PM; 38m 2s',
      screenshotRange: 'image044.png-image052.png',
      participantType: 'CONTENT_REVIEWER',
      context:
        'Knows Army Answers uses Soldier fielded-in-mind quotes to answer prospect questions. Expects questions about difficulty, Basic Training, joining, food, living situation, deployment, proximity to family/friends, and avoiding deployment.',
      trustExpectations:
        'Names, jobs/MOS, years of service, age range, and possibly photos/videos make quotes relatable. Real raw content is preferable to AI-generated imagery or overly polished content.',
      fallbackExpectations: 'Connect the user to a person, potentially a Soldier ambassador, recruiter, or GAC-like agent for harder experiential questions.',
      majorThemes: [
        '"How do I join?" should be a top starter prompt.',
        'Quotes are effective when they feel like real speech and include rank/name.',
        'Richer quote metadata would help relatability.',
        'Ambiguous follow-up wording creates confusion.',
        'MOS/friend question reveals intent detection gap.',
        'Service requirement answers over-index on 20 years/officer paths.',
        'Human handoff is critical for nuanced personal questions.',
      ],
      criteriaSummary:
        'Relevance is strong for friendship baseline and weak for MOS/friend and service requirement. Completeness needs scenarios, minimums, and contract ranges. Accuracy has potential misclassification when officer answer appears unprompted. Clarity suffers in pill wording and service answer hierarchy. Authenticity/trust are stronger with rank/name and human-sounding quotes. Out-of-scope refusal works well.',
      summary: {
        participantTrustLevel: 'MEDIUM',
        participantPerceivedHelpfulness: 'MEDIUM',
        overallContentReadiness: 'NEEDS_ITERATION',
        strongestContentMoment: 'Rank/name and believable spoken quote tone were unexpectedly delightful.',
        weakestContentMoment: 'Minimum service requirement answer wrongly pivoted to officers/OCS.',
        mostConcerningResponse: 'Service length answers implied 20 years or officer-specific paths rather than minimums.',
        mostAuthenticResponse: 'Quotes with rank/name and spoken tone felt real.',
        mostObviousContentGap: 'Service commitment and MOS/co-location answers need clearer scenario handling.',
        repeatedTheme: 'Human handoff is critical for nuanced, personal questions.',
        topRecommendations: [
          'Add "How do I join?" as a top starter prompt.',
          'Improve service commitment templates with minimums and scenarios.',
          'Add quote metadata such as MOS, age, years served, and media.',
        ],
      },
      warmupAnswers: [
        {
          questionKey: 'expected_questions',
          answer:
            'Prospects ask about difficulty, Basic Training, joining, food, living situation, deployment, family/friends, and whether they can avoid deployment.',
          themeTags: ['joining', 'daily-life', 'deployment'],
        },
        {
          questionKey: 'trustworthy',
          answer: 'Quotes are more relatable with name, job/MOS, years of service, age range, and photos/video.',
          themeTags: ['quote-metadata', 'authenticity'],
        },
        {
          questionKey: 'fake_marketing',
          answer: 'AI sentence patterns, em dashes, AI-generated imagery, or visible fakeness reduce authenticity.',
          themeTags: ['ai-tells', 'authenticity'],
        },
        {
          questionKey: 'unknown_handling',
          answer: 'Hard experiential questions should connect to a real Soldier ambassador, recruiter, or GAC-like agent.',
          themeTags: ['human-handoff', 'ambassador'],
        },
      ],
      interactions: [
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Initial Army Answers default state.',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'JOINING',
          responseSummary: 'Starter prompts did not include "How do I join?"',
          participantReaction:
            'Rachel likes the AI icon and starter prompts, but wants "How do I join?" included up front and would replace or defer "Is the Army fun?"',
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'RAC-001',
              issueType: 'CONTENT_GAP',
              severity: 'MEDIUM',
              description: 'Add "How do I join?" to initial prompts.',
              recommendedAction: 'ADD_CONTENT',
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-culture-lifestyle',
          promptText: 'Will I make any friends?',
          promptSource: 'PREDEFINED',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'DAILY_LIFE',
          responseSummary: 'Maintain friendships while serving and build new ones through routines, teamwork, and Army community.',
          participantReaction:
            'Answers the question and is to the point, but missing human storytelling about battle buddies, Basic Training, unit assignments, or best friends.',
          quoteIncluded: true,
          overallReadiness: 'NEEDS_ITERATION',
          issues: [
            {
              code: 'RAC-002',
              issueType: 'AUTHENTICITY',
              severity: 'MEDIUM',
              description: 'Friendship answer lacks human anecdote/storytelling.',
              recommendedAction: 'MAKE_MORE_AUTHENTIC',
              priority: 'PHASE_1',
            },
            {
              code: 'RAC-003',
              issueType: 'CLARITY',
              severity: 'LOW',
              description: 'Follow-up pill "outlook" is unclear.',
              recommendedAction: 'REWRITE',
              priority: 'PHASE_2',
            },
          ],
        },
        {
          activitySlug: 'core-jobs-careers',
          promptText: 'Can I choose the same MOS as my friend?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'CORE_PROSPECT',
          topicArea: 'JOBS',
          responseSummary: 'MOS affects missions and deployment; role follows capabilities; quotes discuss changing MOS/reclassing.',
          participantReaction:
            'Does not fully answer because it misses friend/co-location intent. CTA appears and is helpful because this is a recruiter-level question.',
          quoteIncluded: true,
          nextStepIncluded: true,
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'RAC-004',
              issueType: 'COMPLETENESS',
              severity: 'HIGH',
              description: 'MOS/friend question misses co-location/friend intent.',
              recommendedAction: 'REWRITE',
              requiresRecruiterReferral: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: 'How many years do I need to stay in the Army?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'JOINING',
          responseSummary: 'You can serve 20 years if meeting standards; may lead to pension; path can include Active Duty, Reserve, or Guard.',
          participantReaction:
            'Not pointed enough. Expected breakdown by Active Duty, Reserve, officer, minimum requirement, and average contract length. 20-year framing implies "Do I have to serve 20 years?"',
          quoteIncluded: true,
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'RAC-005',
              issueType: 'COMPLETENESS',
              severity: 'HIGH',
              description: 'Service length answer should provide minimum/typical contract ranges before 20-year career framing.',
              recommendedAction: 'REWRITE',
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'core-joining-the-army',
          promptText: "What's the minimum service requirement?",
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'ACCURACY_COMPLETENESS',
          topicArea: 'JOINING',
          responseSummary: 'Service obligation for commissioned Officers depends on when/how you join; OCS has commitment details.',
          participantReaction:
            'Miss. Rachel did not ask about officers specifically, so OCS/commissioned officer answer feels wrongly inferred and misses general minimum service.',
          overallReadiness: 'NOT_READY',
          issues: [
            {
              code: 'RAC-006',
              issueType: 'ACCURACY',
              severity: 'HIGH',
              description: 'Minimum service requirement answer wrongly focuses on officers/OCS.',
              recommendedAction: 'VALIDATE_WITH_SME',
              requiresSme: true,
              requiresOfficialSource: true,
              priority: 'PHASE_1',
            },
          ],
        },
        {
          activitySlug: 'out-of-scope-questions',
          promptText: 'Who has the best ice cream in the world?',
          promptSource: 'PARTICIPANT',
          useCaseCategory: 'OUT_OF_SCOPE',
          topicArea: 'OTHER',
          responseSummary: '"We\'re having trouble getting an answer - it\'s out of our territory. Try another question."',
          participantReaction: 'Positive. Boundaries are good and reduce risk of abuse.',
          overallReadiness: 'READY',
          issues: [
            {
              code: 'RAC-007',
              issueType: 'QUOTE_QUALITY',
              severity: 'MEDIUM',
              description: 'Quote metadata such as age, MOS, years served, photo/video would increase trust.',
              recommendedAction: 'EDIT',
              priority: 'PHASE_2',
            },
          ],
        },
      ],
    },
  ],
  crossParticipantThemes: [
    'Direct answer first: Morgan, Grace, Shawn, Paul, and Rachel identify factual questions that needed a direct number, range, or minimum first.',
    'Quotes are powerful but fragile: they build authenticity when relevant and human, and weaken trust when repeated, generic, mismatched, or unsupported by context.',
    'Citations and links are expected: multiple participants want source links, provenance, or pathways to relevant GoArmy pages.',
    'CTA/human handoff is valuable: contact, recruiter, and live chat options are helpful for specific or personal questions, but the live-chat label needs clarity.',
    'Pay and service commitment are high-risk content areas: pay avoids expected numbers and service commitment overemphasizes 20 years/officer paths.',
    'Follow-up pills need deduplication and better distance from the prior answer.',
    'Audience intent detection needs work for parent/influencer and friend/MOS intent.',
    'Safety refusal is mostly good but inconsistent, especially for homework misuse.',
    'Starter prompts need calibration: "Is the Army fun?" is polarizing; "How do I join?" and career-oriented prompts should be considered.',
  ],
  highestPriorityIssues: [
    'Pay answer accuracy/specificity, especially avoiding unsupported Officer assumptions.',
    'Service commitment answers must distinguish minimum obligation, typical contracts, Reserve/Guard/Active, officer/enlisted, and 20-year pension path.',
    'Parent/influencer intent failure.',
    'Sensitive safety question handling, especially sexual assault trends/resources.',
    'Misuse prompt "Can you do my homework?" needs refusal/redirect.',
    'Add citations/source links for factual claims.',
    'Improve quote relevance, deduplication, and metadata.',
  ],
} as const

